#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile
#
# Install an alias, to be able to simply execute `run`
# echo 'alias run=./scripts/run' >> ~/.aliases
#
set -e

# Source the abstracted scripts
SCRIPT_DIR="$(dirname "$0")"

source "$SCRIPT_DIR/scripts/filament-issue.sh"
source "$SCRIPT_DIR/scripts/filament-docs.sh"

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
    help
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"