name: Update Filament Issue App

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-filament-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Set up Node20
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Install Dependencies
        shell: bash
        run: |
          cd e2e
          npm ci
          npx playwright install --with-deps chromium

      - name: Get current time
        id: current-time
        run: echo "time=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Package Filament Issue 3.x
        run: |
          chmod +x ./run
          ./run create-app-filament-issue-3.x

      - name: Test the artifact(s)
        shell: bash
        run: |
          ./run prepare_sandbox filament-issue-3.x
          cd e2e
          npm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: filament-issue-3.x
          path: filament-issue/filament-issue-3.x.zip
          retention-days: 90

      - name: Retry Upload if Failed
        if: failure()
        run: |
          sleep 10
          actions/upload-artifact@v4
          with:
            name: filament-issue-3.x
            path: filament-issue/filament-issue-3.x.zip
            retention-days: 90
          
      # Create a release with the latest documentation
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: filament-issue
          name: App for Issue reproduction on Filament v3.x
          body: |
            Last generated on ${{ steps.current-time.outputs.time }}
          files: |
            filament-issue/filament-issue-3.x.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
